/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenTokenIdRouteImport } from './routes/token/$tokenId'
import { Route as TokenNewRouteImport } from './routes/token/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenTokenIdRoute = TokenTokenIdRouteImport.update({
  id: '/token/$tokenId',
  path: '/token/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenNewRoute = TokenNewRouteImport.update({
  id: '/token/new',
  path: '/token/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
  '/token/new': typeof TokenNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
  '/token/new': typeof TokenNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
  '/token/new': typeof TokenNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/token/$tokenId' | '/token/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/token/$tokenId' | '/token/new'
  id: '__root__' | '/' | '/token/$tokenId' | '/token/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TokenTokenIdRoute: typeof TokenTokenIdRoute
  TokenNewRoute: typeof TokenNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$tokenId': {
      id: '/token/$tokenId'
      path: '/token/$tokenId'
      fullPath: '/token/$tokenId'
      preLoaderRoute: typeof TokenTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/new': {
      id: '/token/new'
      path: '/token/new'
      fullPath: '/token/new'
      preLoaderRoute: typeof TokenNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TokenTokenIdRoute: TokenTokenIdRoute,
  TokenNewRoute: TokenNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
