/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenTokenIdRouteImport } from './routes/token/$tokenId'
import { Route as TokenNewRouteImport } from './routes/token/new'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth/change-password'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiCronPollUsageRouteImport } from './routes/api/cron/poll-usage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenTokenIdRoute = TokenTokenIdRouteImport.update({
  id: '/token/$tokenId',
  path: '/token/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenNewRoute = TokenNewRouteImport.update({
  id: '/token/new',
  path: '/token/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPollUsageRoute = ApiCronPollUsageRouteImport.update({
  id: '/api/cron/poll-usage',
  path: '/api/cron/poll-usage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
  '/token/new': typeof TokenNewRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/cron/poll-usage': typeof ApiCronPollUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
  '/token/new': typeof TokenNewRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/cron/poll-usage': typeof ApiCronPollUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
  '/token/new': typeof TokenNewRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/cron/poll-usage': typeof ApiCronPollUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/token/$tokenId'
    | '/token/new'
    | '/api/auth/change-password'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/cron/poll-usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/token/$tokenId'
    | '/token/new'
    | '/api/auth/change-password'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/cron/poll-usage'
  id:
    | '__root__'
    | '/'
    | '/token/$tokenId'
    | '/token/new'
    | '/api/auth/change-password'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/cron/poll-usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TokenTokenIdRoute: typeof TokenTokenIdRoute
  TokenNewRoute: typeof TokenNewRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiCronPollUsageRoute: typeof ApiCronPollUsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$tokenId': {
      id: '/token/$tokenId'
      path: '/token/$tokenId'
      fullPath: '/token/$tokenId'
      preLoaderRoute: typeof TokenTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/new': {
      id: '/token/new'
      path: '/token/new'
      fullPath: '/token/new'
      preLoaderRoute: typeof TokenNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/poll-usage': {
      id: '/api/cron/poll-usage'
      path: '/api/cron/poll-usage'
      fullPath: '/api/cron/poll-usage'
      preLoaderRoute: typeof ApiCronPollUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TokenTokenIdRoute: TokenTokenIdRoute,
  TokenNewRoute: TokenNewRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiCronPollUsageRoute: ApiCronPollUsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
